{block content}

<div class="span-19">
    <h3 class="flaground shadow-rb">{$activeCourse['label']}</h3>
</div>
{for $i=1;$i<=6;$i++}
<!-- Lesson -->
<div class="span-19">
    <div class="lesson flaground shadow-rb">
            <h4>Lesson {$i}</h4>
            <div class="date">12.3.2011</div>
            <div class="summary">Blablabla</div>
            <div class="materials">Materials</div>
    </div>
</div>
{/for}

{/block}


{block head}

{/block}