{**
* My Application layout template.
*
* @copyright  Copyright (c) 2010 John Doe
* @package    MyApplication
*
* @param string   $basePath web base path
* @param string   $robots   tell robots how to index the content of a page (optional)
* @param array    $flashes  flash messages
*}

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <meta name="description" content="Nette Framework web application skeleton">
        <meta name="robots" content="{$robots}" n:ifset="$robots">

        <title>Course Manager</title>

        <!-- import BluePrint CSS framework -->
        <link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/blueprint/screen.css" type="text/css">
        <link rel="stylesheet" media="print" href="{$basePath}/css/blueprint/print.css" type="text/css">
        <!--[if IE]><link rel="stylesheet" href="{$basePath}/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
        <!-- import custom CSS styles -->
        <link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">
        <link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">


        <link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
        <script type="text/javascript" src="{$basePath}/js/netteForms.js"></script>
	{block head}{/block}
    </head>

    <body>
        <div n:foreach="$flashes as $flash" class="flash {$flash->type}">{$flash->message}</div>
        <div class="container">
            <div id="header" class="span-24 last shadow-pull">
                <h1>Course Manager</h1>
                <div id="loginpart">
                    {if $logged}
                    Logged as {$user->email} <br/>
                    <a href="{link user:logout}">logout</a>
                    {else}
                    {widget signInForm} <br />
                    <a href="{link user:register}">register</a>
                    {/if}   

                </div>
            </div>
            <div class="span-19 colborder" id="content">
                {include #content}
            </div>

            <div class="span-4 last" id="sidebar">
                {if $logged}
                    <div id="courselist">
                        <h3 class="caps">My courses</h3>
                        {foreach $courses as $course}
                            <div class="div-course shadow-rb">
                                <a href="">{$course['name']}</a>
                                <div class="italic">{$course['description']}</div>
                                <ul>
                                    <li><a href="">Classes</a></li>
                                    <li><a href="">Statistics</a></li>
                                    <li><a href="">Assignments</a></li>
                                    <li><a href="">Calendar</a></li>
                                </ul>
                            </div>
                        {/foreach}
                    </div>
                {/if}
            </div>
        </div>
    </body>
</html>
